import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className="max-w-screen-md m-auto p-4`">
    
      <main>
        <Link href="/">
        <h1 className="font-bold text-3xl">Dogs breeds</h1>
        </Link>
        <nav>
          <ul className="flex gap-4">
            <li>
              <Link href="/african"> african</Link>
            </li>
            <li>
              <Link href="/airedale"> airedale</Link>
            </li>
            <li>
              <Link href="/affenpinscher"> affenpinscher</Link>
            </li>
          </ul>
        </nav>
        {children}
      </main>
      </body>
    </html>
  );
}
