

import "./globals.css";
import Header from "@/components/Header";
import type { Metadata } from "next";
import FavoritesList from "@/components/FavoritesList";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="max-w-screen-md m-auto p-4`">
        <main>
          <Header />
          <article>{children}</article>
          <hr />
          <FavoritesList />
        </main>
      </body>
    </html>
  );
}
